[global]
ignore_file = "README.md, Makefile.ini, Makefile, configure";
ignore_dir = ".git";

[target#0]
target = "/usr/local/wikiswan/data/pages/%E7%BC%96%E7%A0%81%E8%A7%84%E8%8C%83";  
target_param = "644"  
target_user = "swan";
target_group = "swan";
target_dir_param = "755"
target_dir_user = "swan";
target_dir_group = "swan";