[global]
ignore_file = "README.md, Makefile.ini, Makefile, configure";
ignore_dir = ".git";

[target#0]
target = "/usr/local/wikiswan/data/pages/%E8%B5%84%E6%BA%90";  
target_param = "644"  
target_user = "swan";
target_group = "swan";
target_dir_param = "755"
target_dir_user = "swan";
target_dir_group = "swan";